### Instructions for downloading versions of Firefox
# * Download the desired version from https://ftp.mozilla.org/pub/firefox/releases/
# * Use the linux-x86_64 version
# * untar the downloaded file using: tar -xjf [filename]
# * For use with karma-firefox-launcher, set the PATH environment variable to the firefox binary in the same command as npm run test

### Instructions for downloading versions of Chromium
# * Go here for "official" instructions (honestly, downloading Chromium versions is kind of messy): https://www.chromium.org/getting-involved/download-chromium
# * Use this to get the branch_base_position: https://omahaproxy.appspot.com/
# * Take the branch_base_position number and search for it here: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/
# * If it doesn't come up, you'll just have to increment or decrement the number until you find a match with the correct version of CHROMIUM_BIN
# * Once you've found the correct number, put it into this URL in place of [branch_base_position]: https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F[branch_base_position]%2Fchrome-linux.zip?alt=media
# * Use the unzip command to unzip the file
# * For use with karma-chrome-launcher, set the CHROMIUM_BIN environment variable, using the export command, to the chrome binary

version: 2

jobs:
    build:
        working_directory: ~/assessml
        docker:
            - image: circleci/node:8.17.0@sha256:44c6136b6b55003fa12321aa1eb790a5a6482edb461227cb56daf488178d04dc
        steps:
            - checkout
            - run:
                name: Set permissions
                command: sudo chown -R circleci /usr/local/lib/node_modules && sudo chown -R circleci /usr/local/bin
            - run:
                name: Install Chromium 65
                command: wget https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F530372%2Fchrome-linux.zip?alt=media && unzip Linux_x64%2F530372%2Fchrome-linux.zip?alt=media
            - run:
                name: Install Chromium dependencies
                command: sudo apt-get update && sudo apt-get install libxcomposite1 libxcursor1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0
            - run:
                name: Install Firefox 59
                command: wget https://ftp.mozilla.org/pub/firefox/releases/59.0.2/linux-x86_64/en-US/firefox-59.0.2.tar.bz2 && tar -xjf firefox-59.0.2.tar.bz2
            - run:
               name: Install Firefox dependencies
               command: sudo apt-get update && sudo apt-get install libgtk-3-dev
            - run: npm install
            - run: PATH=$PATH:~/assessml/firefox && export CHROMIUM_BIN=~/assessml/chrome-linux/chrome && npm test
